/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BearbeitungRouteImport } from './routes/bearbeitung'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as TelefonDemoRouteImport } from './routes/telefon-demo'
import { Route as ApiBeschwerdenRouteImport } from './routes/api/beschwerden'
import { Route as ApiGesundheitRouteImport } from './routes/api/gesundheit'
import { Route as ApiTelefonAntwortRouteImport } from './routes/api/telefon/antwort'
import { Route as ApiTelefonChatRouteImport } from './routes/api/telefon/chat'
import { Route as ApiTelefonSprechenRouteImport } from './routes/api/telefon/sprechen'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BearbeitungRoute = BearbeitungRouteImport.update({
  id: '/bearbeitung',
  path: '/bearbeitung',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const TelefonDemoRoute = TelefonDemoRouteImport.update({
  id: '/telefon-demo',
  path: '/telefon-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBeschwerdenRoute = ApiBeschwerdenRouteImport.update({
  id: '/api/beschwerden',
  path: '/api/beschwerden',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGesundheitRoute = ApiGesundheitRouteImport.update({
  id: '/api/gesundheit',
  path: '/api/gesundheit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelefonAntwortRoute = ApiTelefonAntwortRouteImport.update({
  id: '/api/telefon/antwort',
  path: '/api/telefon/antwort',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelefonChatRoute = ApiTelefonChatRouteImport.update({
  id: '/api/telefon/chat',
  path: '/api/telefon/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelefonSprechenRoute = ApiTelefonSprechenRouteImport.update({
  id: '/api/telefon/sprechen',
  path: '/api/telefon/sprechen',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bearbeitung': typeof BearbeitungRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/telefon-demo': typeof TelefonDemoRoute
  '/api/beschwerden': typeof ApiBeschwerdenRoute
  '/api/gesundheit': typeof ApiGesundheitRoute
  '/api/telefon/antwort': typeof ApiTelefonAntwortRoute
  '/api/telefon/chat': typeof ApiTelefonChatRoute
  '/api/telefon/sprechen': typeof ApiTelefonSprechenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bearbeitung': typeof BearbeitungRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/telefon-demo': typeof TelefonDemoRoute
  '/api/beschwerden': typeof ApiBeschwerdenRoute
  '/api/gesundheit': typeof ApiGesundheitRoute
  '/api/telefon/antwort': typeof ApiTelefonAntwortRoute
  '/api/telefon/chat': typeof ApiTelefonChatRoute
  '/api/telefon/sprechen': typeof ApiTelefonSprechenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bearbeitung': typeof BearbeitungRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/telefon-demo': typeof TelefonDemoRoute
  '/api/beschwerden': typeof ApiBeschwerdenRoute
  '/api/gesundheit': typeof ApiGesundheitRoute
  '/api/telefon/antwort': typeof ApiTelefonAntwortRoute
  '/api/telefon/chat': typeof ApiTelefonChatRoute
  '/api/telefon/sprechen': typeof ApiTelefonSprechenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bearbeitung'
    | '/datenschutz'
    | '/impressum'
    | '/telefon-demo'
    | '/api/beschwerden'
    | '/api/gesundheit'
    | '/api/telefon/antwort'
    | '/api/telefon/chat'
    | '/api/telefon/sprechen'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bearbeitung'
    | '/datenschutz'
    | '/impressum'
    | '/telefon-demo'
    | '/api/beschwerden'
    | '/api/gesundheit'
    | '/api/telefon/antwort'
    | '/api/telefon/chat'
    | '/api/telefon/sprechen'
  id:
    | '__root__'
    | '/'
    | '/bearbeitung'
    | '/datenschutz'
    | '/impressum'
    | '/telefon-demo'
    | '/api/beschwerden'
    | '/api/gesundheit'
    | '/api/telefon/antwort'
    | '/api/telefon/chat'
    | '/api/telefon/sprechen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BearbeitungRoute: typeof BearbeitungRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  TelefonDemoRoute: typeof TelefonDemoRoute
  ApiBeschwerdenRoute: typeof ApiBeschwerdenRoute
  ApiGesundheitRoute: typeof ApiGesundheitRoute
  ApiTelefonAntwortRoute: typeof ApiTelefonAntwortRoute
  ApiTelefonChatRoute: typeof ApiTelefonChatRoute
  ApiTelefonSprechenRoute: typeof ApiTelefonSprechenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bearbeitung': {
      id: '/bearbeitung'
      path: '/bearbeitung'
      fullPath: '/bearbeitung'
      preLoaderRoute: typeof BearbeitungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telefon-demo': {
      id: '/telefon-demo'
      path: '/telefon-demo'
      fullPath: '/telefon-demo'
      preLoaderRoute: typeof TelefonDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/beschwerden': {
      id: '/api/beschwerden'
      path: '/api/beschwerden'
      fullPath: '/api/beschwerden'
      preLoaderRoute: typeof ApiBeschwerdenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gesundheit': {
      id: '/api/gesundheit'
      path: '/api/gesundheit'
      fullPath: '/api/gesundheit'
      preLoaderRoute: typeof ApiGesundheitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telefon/antwort': {
      id: '/api/telefon/antwort'
      path: '/api/telefon/antwort'
      fullPath: '/api/telefon/antwort'
      preLoaderRoute: typeof ApiTelefonAntwortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telefon/chat': {
      id: '/api/telefon/chat'
      path: '/api/telefon/chat'
      fullPath: '/api/telefon/chat'
      preLoaderRoute: typeof ApiTelefonChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telefon/sprechen': {
      id: '/api/telefon/sprechen'
      path: '/api/telefon/sprechen'
      fullPath: '/api/telefon/sprechen'
      preLoaderRoute: typeof ApiTelefonSprechenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BearbeitungRoute: BearbeitungRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  TelefonDemoRoute: TelefonDemoRoute,
  ApiBeschwerdenRoute: ApiBeschwerdenRoute,
  ApiGesundheitRoute: ApiGesundheitRoute,
  ApiTelefonAntwortRoute: ApiTelefonAntwortRoute,
  ApiTelefonChatRoute: ApiTelefonChatRoute,
  ApiTelefonSprechenRoute: ApiTelefonSprechenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
